# Generated by Django 6.0.7 on 2026-07-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(blank=True, help_text='Customer email address', max_length=254),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='visit_date',
            field=models.DateField(blank=True, help_text='Preferred visit date', null=True),
        ),
    ]
