# Generated by Django 6.0.7 on 2026-09-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_bookdog_options_alter_enquiry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customergallery',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customer Gallery Item', 'verbose_name_plural': 'Customer Gallery'},
        ),
        migrations.AlterField(
            model_name='customergallery',
            name='caption',
            field=models.CharField(blank=True, max_length=400, verbose_name='Short Story / Caption'),
        ),
        migrations.AlterField(
            model_name='customergallery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Added On'),
        ),
        migrations.AlterField(
            model_name='customergallery',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Customer / Family Name'),
        ),
        migrations.AlterField(
            model_name='customergallery',
            name='dog_breed',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dog / Cat Breed'),
        ),
        migrations.AlterField(
            model_name='customergallery',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload customer photo', null=True, upload_to='customer_gallery/photos/'),
        ),
        migrations.AlterField(
            model_name='customergallery',
            name='video',
            field=models.FileField(blank=True, help_text='Upload customer video (MP4/WebM/MOV)', null=True, upload_to='customer_gallery/videos/'),
        ),
    ]
