# Generated by Django 6.0.7 on 2026-07-12 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Persian Cat', max_length=100)),
                ('breed', models.CharField(blank=True, help_text='Optional extra breed detail, e.g. White Persian', max_length=100)),
                ('age_range', models.CharField(blank=True, help_text='e.g. 6-12 months (optional)', max_length=50)),
                ('size', models.CharField(blank=True, choices=[('', '-- optional --'), ('Toy', 'Toy'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='', max_length=20)),
                ('price_range', models.CharField(help_text='e.g. ₹15,000 - ₹40,000', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cats/')),
                ('image2', models.ImageField(blank=True, help_text='Optional second photo', null=True, upload_to='cats/')),
                ('available', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Labrador Retriever', max_length=100)),
                ('breed', models.CharField(blank=True, help_text='Optional extra breed detail, e.g. Golden Lab', max_length=100)),
                ('age_range', models.CharField(blank=True, help_text='e.g. 3-6 months (optional)', max_length=50)),
                ('size', models.CharField(blank=True, choices=[('', '-- optional --'), ('Toy', 'Toy'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='', max_length=20)),
                ('price_range', models.CharField(help_text='e.g. ₹18,000 to ₹22,000', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dogs/')),
                ('image2', models.ImageField(blank=True, help_text='Optional second photo', null=True, upload_to='dogs/')),
                ('available', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('breed', models.CharField(blank=True, help_text='Breed the customer is interested in', max_length=100)),
                ('message', models.TextField()),
                ('contacted', models.BooleanField(default=False, help_text="Tick once you've followed up with the customer")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField()),
                ('approved', models.BooleanField(default=True, help_text='Untick to hide this review from the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
