# Generated by Django 6.0.7 on 2026-09-03 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bookdog_customergallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookdog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dog Booking Request', 'verbose_name_plural': 'Dog Booking Requests'},
        ),
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact / General Enquiry', 'verbose_name_plural': 'Contact & Enquiries'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customer Review', 'verbose_name_plural': 'Customer Reviews'},
        ),
        migrations.AddField(
            model_name='bookdog',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ Pending'), ('contacted', '📞 Contacted'), ('confirmed', '✅ Confirmed'), ('cancelled', '❌ Cancelled')], default='pending', max_length=20, verbose_name='Booking Status'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('new', '🆕 New'), ('in_progress', '⏳ In Progress'), ('contacted', '📞 Contacted'), ('closed', '✅ Closed')], default='new', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='review',
            name='dog_breed',
            field=models.CharField(blank=True, max_length=150, verbose_name='Pet Breed Adopted'),
        ),
        migrations.AlterField(
            model_name='bookdog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Submitted On'),
        ),
        migrations.AlterField(
            model_name='bookdog',
            name='dog_breed',
            field=models.CharField(blank=True, max_length=200, verbose_name='Interested Breed'),
        ),
        migrations.AlterField(
            model_name='bookdog',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='bookdog',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='bookdog',
            name='message',
            field=models.TextField(blank=True, verbose_name='Notes / Preferences'),
        ),
        migrations.AlterField(
            model_name='bookdog',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Phone / WhatsApp'),
        ),
        migrations.AlterField(
            model_name='bookdog',
            name='visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Preferred Date'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='age_range',
            field=models.CharField(blank=True, help_text='e.g. 2-4 months', max_length=50),
        ),
        migrations.AlterField(
            model_name='cat',
            name='breed',
            field=models.CharField(blank=True, help_text='Optional extra breed detail, e.g. Doll Face White', max_length=100),
        ),
        migrations.AlterField(
            model_name='cat',
            name='price_range',
            field=models.CharField(help_text='e.g. ₹15,000 - ₹35,000', max_length=100),
        ),
        migrations.AlterField(
            model_name='dog',
            name='age_range',
            field=models.CharField(blank=True, help_text='e.g. 2-3 months', max_length=50),
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(blank=True, help_text='Optional extra breed detail, e.g. Working Line', max_length=100),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(help_text='e.g. German Shepherd', max_length=100),
        ),
        migrations.AlterField(
            model_name='dog',
            name='price_range',
            field=models.CharField(help_text='e.g. ₹18,000 to ₹25,000', max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='breed',
            field=models.CharField(blank=True, max_length=100, verbose_name='Interested Breed'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='contacted',
            field=models.BooleanField(default=False, help_text='Mark when customer is contacted', verbose_name='Contacted'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Received On'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='message',
            field=models.TextField(verbose_name='Message / Enquiry'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(max_length=25, verbose_name='Phone / WhatsApp'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Visit Date'),
        ),
        migrations.AlterField(
            model_name='review',
            name='approved',
            field=models.BooleanField(default=True, help_text='Check to display this review live on the website', verbose_name='Approved / Live'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Submitted On'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating (1-5)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='Review Message'),
        ),
    ]
