# Generated by Django 6.0.7 on 2026-09-06 07:44

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_customergallery_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customergallery',
            name='video',
            field=models.FileField(blank=True, help_text='Upload customer video (MP4/WebM/MOV)', null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='customer_gallery/videos/'),
        ),
    ]
